YOUR_DB_HOST = 'localhost'
YOUR_DB_PORT = 'YOUR_DB_PORT'
YOUR_DB_NAME = 'YOUR_DB_NAME'
YOUR_DB_USER = 'postgres'
YOUR_DB_PASSWORD = 'YOUR_DB_PASSWORD'

YOUR_OPENAI_API_KEY = 'YOUR_OPENAI_API_KEY'
YOUR_OPENAI_API_ORGANIZATION = 'YOUR_OPENAI_API_ORGANIZATION'
MODEL_3_5 = "gpt-3.5-turbo"